#include <stdio.h>
#include <stdlib.h>



void easterEgg () {
system("resize -s 45 100");
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNmmNNmmmmNNNNMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNmmhyso++oo++/++oyhmmNNMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNy/:-..`....----:/+shdmmNNNMMMMMNmNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmo-...`````......-:/oyddmNNNNMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNy-...``````````...-:/oyhdNNNMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNo..````````````...-:/osyhmNNMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN+..`````````.....--:/osyhNNNMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNo-.`````````.``...-:/oydmNNMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNmmm+...```````````.-/shhdmmmNNNNNNMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmN+.-://+oso:...-/smNmhmmmdydmNNNMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNmmmmNNmmmmmdy-.../symho:..-sdNNy+hdmmhhmNNNMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmNmmy-::..:+:/oo+-..-smdmhsosssshdmNNNMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmm---....--:--...:yNmh+//++osydNNMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmo`...``........-omNmy/:/+oshmNMMMMMMMNmNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmh.-.``````..-..-yNNNNm+/+shmNNMMMMMMMNmNNNNNNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmm+`.`````--.:::+hmNNNdy+/odNNMMMMMNNNmmNmmmmNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmh.-.....://oyyyohmmmNNNmhdNMMMMMMNmmNNmmmmmmNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmdh/...-os+:::/+oyyhNNmdNmMMMMMMNmmmNNNmmmmNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmd+:.-so/+/---:+oshhssdmMMMMMMNmmNmNNmmmmNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmhoyo+so...--//+yhdyyhmNMMMMMNmmmmNNNmmmmNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmms`-mmhys:...-://+++smNMMMMMMMNmmmmNNNmmmmNNNNNmNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNmNNmmmmmmmmmmmmmmmmmmmmd/` .Nhymdy+/:-:/+oydmNMMMMMMMMMNmmmmNNmmmmNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmNNNd.   `Ny./ydhhhsyddmNNMMMNNNNNNMMNmmmmmmmmmmNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNNNNmmmmmmmNmmmmmNNNNNNNNd.     hh...:+yhmmNNNNNNNNNNNNNNMMNmmmmmmmNNmNNNNNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNNNNmmmmmmmmmmmNNNNNNNNNNNNN:      +N:```..--/+sydmmmmmmmmmmMmmNNmNNmNmmNNNmmNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNNmmmmmmmmmmhydNNNNNNNNNNNNNd`      -dd-```..`.-:/shddhyyyhhdy:hNNmNMNNNmmmmmmNNNNNNNNNNNNNNNN\n" );
printf("NNNNNNNmmmmmmhyo:-..mNNNNNNNNNNNNmo       `/Nd:.``...:+ssyhs++ooooo.`+mmmNMMMMNNNmmmNNNNNNNNNNNNNNNN\n" );
printf("NNNNNmmmmh+:.``    `mNNNNNNNNNNmmm-     -ohsoNms-...-/+++oo+/+++//-` :dmmmNMMMMMMNNNmmmNNNNNNNNNNNNN\n" );
printf("NNNNmmms-`         `mNNNNNNNNNNmmm`   -hNMNh-omNdo-..--:/+////+:-:.` :ymmNmMMMMMMMMMNNNNNNNNNNNNNNNN\n" );
printf("Nmmmms-            `mNmNNNNNNNmmms  .sNMMMd-.`/dNNh+:--::--:++:.``:hhoshmmNNMMMMMMMMMMMNmNNNNNNNNNNN\n" );
printf("mmmy-              `mNNNNNNNNNmNm+ :mMMMNNd.   :hdhhs:-...-/:.` .oNMMMNdhmNNMMMMMMMMMMMNmmNNNNNNNNNN\n" );
printf("my:                `mNNNNNNNNmmNmo+NMNNNNNm-   `//.-/s/````   `/dMMMMMMMNyhmNMMMMMMMMMMy/hmmNNNNNNNN\n" );
printf("/`                 `mNNNNNNNNNNNNmNNNNNNNNNy     `-``./`````./hNMMMMMMMMMNhyNMMMMMMMMMm.:++shmNNNNNN\n" );
printf("                   `mNNNNNNNNNNNNNNNNNNNNNNN:     ``-:+o++/:/omMMMMMMNNNNMNsmMMMMMMMMMh`-h.++hmmNNNN\n" );
printf("                   `mmNmNNNNNNNNNNNNNNNNNNNNd`   `.+y/:.`````oNMMMNNNNNNNNNNNMMMMMMMMN/`:h.+/+hhdNmN\n" );
printf("         ``    `   .mmmNNNNNNNNNNNNNNNNNNNNNNs  ``/+.     ``sNMNMNNNNNNNNNNMNNNMMMMMMh-.-y`:///-oNNN\n" );
printf("         -     `   :mNNmNNNNNNNNNNNNNNNNNNNNNm. .-/`     `.yNMMMMMNNNNNNNNNNMMMNNMMMM+s.-+.--:`/:mNN\n" );
printf("        `/         +mmmNNNNNNNNNNNNNNNNNNNNNNNo -:`      -hNMMMNNNNNNNNNNNNNMMMNNNMMN/d`.-.--`/+`mNN\n" );
printf("`       :-       ` smmmNNNNNNNNNNNNNNNNNNNNNNNm-..      .dNMNNMNNNNNNNNNNNNNMMMMMNNNN-N-....`-+:/NNN\n" );
printf("`      .+```  `   `dmmmmNNNNNNNNNNNNNNNNNNNNNNNm:`     :mNMNNNNMNNNNNNNNNNNNNMNMNNNNd-Ns`.` `++:mNNN\n" );
printf("`     `/o `-``    `mmmmNNNNNNNNNNNNNNNNNNNNNNNNNm:    +NNMNNNNNNNNNNNNNNNNNNNMNNNNNNh-Ny`` `-o:hmdNN\n" );
printf("`     -o/ `--.    -mmmmNNNNNNNNNNNNNNNNNNNNNNNNNNm. `sNNMNNNMNNNNNNNNNNNNNNNNNNMNNNMN-dy```-o-yyomNN\n" );
printf(".`   ./s```.y.    +mmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNd-dNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMM+h+``:+--/yNNmm\n" );
printf("GRACIAS POR ESTE SEMESTRE Y POR ESNEÑARNOS APESAR DE LAS CIRCUNSTACIAS!!!!!\n" );

}
